import Head from "next/head";
import Image from "next/image";
import About from "../components/About";
import Content from "../components/Content";
import Main from "../components/Main";
import Projects from "../components/Projects";
import Skills from "../components/Skills";
import PdfButtom from "../components/PdfButtom";

export default function Home() {
  return (
    <div className="container mx-auto px-4 md:px-6">
      <Head>
        <title>clint | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/android.ico" />
      </Head>
      <Main />
      <About />
      <Skills />
      <Projects />
      <Content />
    </div>
  );
}
