import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Content from '../components/Content'
import Main from '../components/Main'
import Projects from '../components/Projects'
import Skills from '../components/Skills'

export default function Home() {
  return (
    <div >
      <Head>
        <title>clint | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/android.ico" />
      </Head>
    <Main/>
    <About/>
    <Skills/>
    <Projects/>
    <Content/>
    </div>
  )
}
